apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
spec: 
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/disk1/
  claimRef:
    name: 
    namespace: prod
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker-01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  namespace: prod
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: es-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: es
  namespace: prod
spec:
  encryptedData:
    cassandra-password: AgAzDGNyI+ToKShMG1MLmME+X7Foi40ZrIZT71qe8aMZgpEZPQx3EylOClQLSeCVcMnMcGjikLp5LEoPXR9FUEf1u+yhYJ2hREMFOetciLriU7lHMyAUnqbJNSXROFOxiw0XGNv/lwK4QVKHPeyPlXE9L1X4zdqdvJ5YYR1Z+ttKSUEzxYsKiUu4GPAfyovfHG68mCCaHNhg1c23gT/aV8TES9xkuLGCjvoVkEWPn+JAn1ceueNmOrTfiMYW7kAqG2orvVIkokm25LSMLsFO1UomdA3iJFK2Mh8NzVoaEFO3u3rEDDCKGMLJnfvHCPO0qOepeOpWqN7lmX2v1J6NOMzr+5/f9JfvZS0ba6SioD2cggOqJ9xAifp25hL0hqqvMv4SpDugH8GHaD1GyytOfasfwjp77FPlCyMEL0aiWcA0zNYtGSL0kB89LS54PE4ScGtBccf0XGejGbyeMURGZ7bZ12bRT7kOJCQGVWySh2+8scneHwm6k9fqfeC4t352fQqVDgac9YAhi88k0AXnic67ss8l9bHQg+ENcGGM5fhQM2YzXZ40y0Y88zseqCDBh0LWAMV2iFLgK3slOKXqe3oczyhUTteFDAZdXgPWhn3UrEhee30Ocr6agvKcJijiBaBwDuEK9mC6jD02D/OeR1dKfQax+2dfW9SJk4+c8qQmfpSaMEKFzBJdjt1CnRtmQLTKqprZQNAXng==
  template:
    metadata:
      name: es
      namespace: prod