---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-app
  namespace: prod
spec:
  interval: 30s
  targetNamespace: prod
  sourceRef:
    kind: GitRepository
    name: prod
  path: "./gitops/apps/test"
  prune: true
  timeout: 1m
