---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-kustomization
  namespace: flux-system
spec:
  interval: 30s
  targetNamespace: prod
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./gitops/apps"
  prune: true
  timeout: 1m
