---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: prod
  namespace: prod
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/JohanHellmark/HomeLab.git
