openapi: "3.0.0"
info:
  version: 1.0.0
  title: Projects
  description: A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification
  termsOfService: https://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: https://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://0.0.0.0:8080/api
paths:
  /projects:
    get:
      summary: Returns a list of the current projects
      description: |
        Returns all of the current projects
      operationId: listProjects
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Project response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Project:
      allOf:
        - $ref: "#/components/schemas/NewProject"
        - required:
            - id
          properties:
            id:
              type: integer
              format: int64
              description: Unique id of the pet
    NewProject:
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the project
        description:
          type: string
          description: A more in depth description of the project
        tag:
          type: string
          description: The tags of the project
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
