// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package api

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// NewProject defines model for NewProject.
type NewProject struct {
	// Description A more in depth description of the project
	Description *string `json:"description,omitempty"`

	// Name Name of the project
	Name string `json:"name"`

	// Tag The tags of the project
	Tag *string `json:"tag,omitempty"`
}

// Project defines model for Project.
type Project struct {
	// Description A more in depth description of the project
	Description *string `json:"description,omitempty"`

	// Id Unique id of the pet
	Id int64 `json:"id"`

	// Name Name of the project
	Name string `json:"name"`

	// Tag The tags of the project
	Tag *string `json:"tag,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Tags tags to filter by
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty"`

	// Limit maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}
