apiVersion: v1
kind: Secret
metadata:
  name: istio
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: istio.io
  url: https://github.com/JohanHellmark/Homelab
  type: helm
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgA78ZGOXPd4LDArL6K/mPffEObVBRx7EdAOdvcgzsT0SndSi9s1I/sJFE6czZw6Vlz7worEadmL8gHbfVCcqNVLs16e+zrzwH4u3P8FGD7cw+9hkZo8kuDeQdVMOQSmtgkkpXzv3J26FnUloTg1o1fFfKCGok8G2HdHfRQxT/9E7vXfmAtZb4BSMAJIoihQYycU4cLnQgKB/xSbTOzJoYcD8G8cchzPYeORRNeEcHLlLJL0XUgELF9kRLNgMh1ZKjhyS/L6BVhV53JrXhxYkrg+offTTIw12001qNOkYjcmGilxYfSyjpHXpQhHfchVX4R7TkEuzViNuv3+Ovp8MoWJykoKIIm4ctyDxQvSSJRpUiX8n2GduDDfmVK7515cXl92bLpYFdC70E+hpEP7WKkv7jeNQVypOteehxWXKaLXQtlPdsodcPgduqLeQyUB6GAzcTgYejaCK87/wtWLP2xwX6R8IXHC7etLbgDEzY7nPzqcCzQonoa3RhxUCoQqyfFuDecHpxOGEFwDzUoea4zj2vLqeACPznlZlUFdJaNFnI96qnCxH3cCspasjOHlx5gVbMVypELgl15MtRX3tER6LQZfxxQZ22b/rm/XP2gy/5Z2MLW28GqN8aJnGLOp8hQOs5fbohGa6h+7HxrP7Co6WVgYsMzTpjutOSD5FrjLQ+J/alCxt36/a25ttSnxNdMO3TqGjHF2kMCFJp2ePdS2lKZV3gG6oeFkP/A9SPEdW+YPJgvedoJdf6mskmZ5vcRmzdfoc2TMhHc2KppaM2hdXjXreZrGx720049oJw6rCO/3r8ZOo/dJUa0NRT5ObZ7f9JlpwEjkv9VV8bVh4osMGyyxNn/ODYnJMQ+H0FKwZpcaFucZFeTfM300RgJF6PEiXBLrimaFskQ0+fTVK/VPQyMeUxITm2lzXY5BSGQ+yzwfkmtZ2sB9xlD1hQ==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  registries.conf: |
    registries:
    - name: Docker Hub
      prefix: docker.io
      api_url: https://docker.io
      credentials: pullsecret:argocd/dockerhub
      defaultns: library
      default: true