apiVersion: v1
kind: Secret
metadata:
  name: istio
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: istio.io
  url: https://github.com/JohanHellmark/Homelab
  type: helm
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCtsrFU3otaO4Iqry4HE0+a8TgZh0WVc4ujIZKo8wRGfIcu3fYB7C86fU0Xs3jHywa2qQXDbkVy90BkWYB7r52hrDOC7M83Ytq0BaAnizDH0u1QuCziq6UldL8vXwDTj9Ryw9b5qULhbUhNVwkd89eL6GNFBvY05CNY/cbzZaiRYqc+UsIE7H9vEEWxz+YYqQLe9ewEEaaVTPStii4hDy2IYUcTReUI04JzFACtzk59YB4uv3y+pf8FPambaeg89BRy3enyOkyG5cbhFATa96bgEpUZPdqkAiUZymB0pRDVTUy1wyAU+5lboOexF4uyMm92aXiIFwnN6rIo2eH8LvsfkCph3NJAp9jwvMUiiy7rwWGm/1CuMpVE3ZdA/tH+S3zVteJBiWmFhcIBEmRrapVTz5N8kwvkmntInHu/V+DXUT3zk6WAC1nMXv+M9eu6f9XbNnOvRufU6Whp4uwcj1tHbh7YNroMfVdeWpwAU08FVpFz2mbOxTcMGw4dbipeFLXstSykQVARZV6K5lTfnflC1ZWO8pQdPYy2m0CE8uqlPo4Db3Lgv/Ej8xa2Qaxrx2caNVBgIr9PRf6Q6Sv+1wzQiF3JkDpKohYTCks9XZwYcDo0+dkpcP/X8XGMfPyfN90TdFSYIv7TDEPm4ytt7NChcdjeC4Mv5B2+RSuAv1KofabxZVqNvuqA39RN97qNyLbkqyE85UyPvgnrkOyTH9zx4kxPG0dIc7dwIlqDfNz3fvwQtPiFVy8eMSyU4giS+9sqYBv46Nxu6A6N+x4cPz+7ApY0OAr15qRfOCDU14bzhuNis8Tq8trp6A7FJXH3pTio1Qtx0236wzDhhf9PL4/QEqJ/fP49zwzLmW3ZePtwStVk7fBPL72YFx+Be3nrKgwnk2n7/dW3fKfCWbG2CjyB5nvi1p/pVXxO3b13Udndupi6HJiKNDLcyKAOug==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub
      namespace: default
    type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  registries.conf: |
    registries:
    - name: Docker Hub
      prefix: docker.io
      api_url: https://docker.io
      credentials: pullsecret:argocd/dockerhub
      defaultns: library
      default: true