---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cassandra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    path: gitops/cassandra
    repoURL: {{ .Values.spec.source.repoURL }}
  destination:
    namespace: prod
    server: {{ .Values.spec.destination.server }}