---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: nats
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: 1.0.2
    helm:
      releaseName: nats
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nats