---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    chart: nats
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: 1.0.2
    helm:
      releaseName: nats
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nats
--- 
apiVersion: v1
kind: Service
metadata:
  name: external-nats
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nats
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 4222
      targetPort: 4222
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 34222