---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    targetRevision: {{ .Values.spec.source.targetRevision }}
    repoURL: {{ .Values.spec.source.repoURL }}
    path: infrastructure/nats
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: nats