---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-telemetry-daemon
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    path: gitops/open-telemetry
    repoURL: {{ .Values.spec.source.repoURL }}
    valueFiles:
      - values-deamon.yaml
  destination:
    namespace: nats-service
    server: {{ .Values.spec.destination.server }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-telemetry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    path: gitops/open-telemetry
    repoURL: {{ .Values.spec.source.repoURL }}
    valueFiles:
      - values-deployment.yaml
  destination:
    namespace: nats-service
    server: {{ .Values.spec.destination.server }}