---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    chart: opentelemetry-collector 
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.68.0
    helm:
      releaseName: otel-collector
      valueFiles:
        - gitops/apps/values/otel-collectory.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: open-telemetry