---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    chart: opentelemetry-collector 
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.67.0
    helm:
      releaseName: otel-collector
      valueFiles:
        - ../values-otel-collector.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: open-telemetry
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  otel-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
spec:
  destination:
    namespace: otel-collector
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: gitops/otel-collector
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}