apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-roller
spec:
  selector:
    matchLabels:
      app: dice-roller
  replicas: 1
  template:
    spec:
      containers:
        - name: dice-roller
          image: ${image}
          imagePullPolicy: IfNotPresent
          command:
            - python3
            - dice_roller/main.py
          resources:
            requests:
              memory: "20Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"
