apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JohanHellmark/HomeLab
    targetRevision: HEAD
    path: gitops/apps/guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook