opentelemetry-collector:
  mode: deployment
  # We only want one of these collectors - any more and we'd produce duplicate data
  replicaCount: 1
  config:
    receivers:
      otlp:
        grpc: 
          endpoint: 0.0.0.0:4317
        http: 
          endpoint: 0.0.0.0:4318
  # presets:
    # enables the k8sclusterreceiver and adds it to the metrics pipelines
    # clusterMetrics:
    #   enabled: true
    # enables the k8sobjectsreceiver to collect events only and adds it to the logs pipelines
    # kubernetesEvents:
    #   enabled: true