opentelemetry-collector:
  mode: daemonset
  config:
    receivers:
      otlp:
        protocols:
          grpc: 
            endpoint: 0.0.0.0:4317
            tls: null
          http: 
    exporters:
      otlp:
        endpoint: "open-telemetry-opentelemetry-collector.monitoring.svc.cluster.local"
        tls: 
          insecure: true
    service:
      pipelines:
        traces:
          exporters: [ otlp ]
        metrics:
          exporters: [ otlp ]
        logs:
          exporters: [ otlp ]
  # extraVolumes:
  #   - name: tls-secret
  #     secret:
  #       secretName: selfsigned-otel
  # extraVolumeMounts:
  #   - name: tls-secret
  #     readOnly: true
  #     mountPath: "/certificate"
  # presets:
    # enables the k8sattributesprocessor and adds it to the traces, metrics, and logs pipelines
    # kubernetesAttributes:
    #   enabled: true
    # # enables the kubeletstatsreceiver and adds it to the metrics pipelines
    # kubeletMetrics:
    #   enabled: true
    # Enables the filelogreceiver and adds it to the logs pipelines
    # logsCollection:
    #   enabled: true
  ## The chart only includes the loggingexporter by default
  ## If you want to send your data somewhere you need to
  ## configure an exporter, such as the otlpexporter