---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dice-roller
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/v1/johanhellmark/dice-roller:main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
spec:
  destination:
    namespace: prod
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: gitops/dice-roller
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}