apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv
spec:
  storageClassName: ""
  claimRef:
    name: cassandra-pv
    namespace: prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
  namespace: prod
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: cassandra-pv
